import React, { useMemo } from 'react';
import * as THREE from 'three';
import { Slab } from './Slab';
import {
  panelPlain,
  panelDots,
  panelMetal,
  panelDoc,
  panelChart,
  panelSolid,
  rng,
} from './faces';

/**
 * The set is a TILED WALL, not a scatter of cards.
 *
 * The per-second A/B analysis named this in 10 of 15 seconds, in near-identical
 * words each time: the reference is a "tight, structured keyboard grid" while
 * this scene "floats cards loosely in 3D space without a physical grid
 * structure". Confirmed at 1:1 — the reference's surface is a strictly
 * axis-aligned mosaic of rectangular tiles butted together with fine seams,
 * every tile coplanar or one small step off its neighbour, and the subjects sit
 * IN it rather than above it.
 *
 * The previous implementation was the opposite of that on every axis: cell
 * centres jittered off their lattice, independently random widths that made
 * tiles overlap and gap, per-tile Y rotation, and heights varying by 2x. That
 * produced the "chaotic overlapping floating collage" the analysis kept
 * reporting.
 *
 * Tiles are now generated by recursive guillotine subdivision, which by
 * construction tiles the plane exactly: no overlaps, no gaps, every edge
 * axis-aligned, and a natural mix of large and small rectangles. Seams come
 * from insetting each tile, so they are even everywhere.
 */

type Kind = 'plain' | 'dots' | 'metal' | 'doc' | 'chart' | 'blue' | 'gold' | 'lightblue';

/** Top of the tiled surface. Everything else in the scene is placed against this. */
export const TILE_TOP = 0;
const TILE_THICK = 0.42;
/** Gap between neighbouring tiles. Fine and even — this is a machined surface. */
const SEAM = 0.026;
/**
 * Smallest tile edge. Below this the wall reads as noise rather than structure.
 *
 * Subdividing harder (depth 8 / 0.52) was tried to close the centre-of-frame
 * edge-detail deficit, and it did raise the number — while turning the lockup
 * wall into a uniform field of small squares, where the reference's tiles are
 * large, calm and varied in size. Laplacian energy rewards high-frequency
 * content regardless of whether it is structure or clutter; that is the third
 * time a metric in this scene has improved as the picture got worse. The grain
 * added to panelPlain is the part of that change worth keeping.
 */
const MIN_TILE = 0.92;

type Tile = { x: number; z: number; w: number; l: number; step: number; kind: Kind };

/**
 * Recursive guillotine subdivision of [x0,x1] x [z0,z1].
 *
 * Splitting the longer side keeps aspect ratios sane; the split fraction is
 * kept away from the ends so no sliver tiles appear. Depth bounds the tile
 * count, and MIN_TILE stops subdivision before tiles get too small to read.
 */
function subdivide(
  x0: number, z0: number, x1: number, z1: number,
  depth: number, r: () => number, out: Array<[number, number, number, number]>,
): void {
  const w = x1 - x0;
  const l = z1 - z0;
  const canX = w >= MIN_TILE * 2;
  const canZ = l >= MIN_TILE * 2;
  if (depth <= 0 || (!canX && !canZ)) {
    out.push([x0, z0, x1, z1]);
    return;
  }
  // Prefer the longer axis, but not slavishly — always alternating produces a
  // visible pinwheel.
  const useX = canX && (!canZ || (w > l * 1.12 ? true : l > w * 1.12 ? false : r() > 0.5));
  const f = 0.36 + r() * 0.28;
  if (useX) {
    const xm = x0 + w * f;
    subdivide(x0, z0, xm, z1, depth - 1, r, out);
    subdivide(xm, z0, x1, z1, depth - 1, r, out);
  } else {
    const zm = z0 + l * f;
    subdivide(x0, z0, x1, zm, depth - 1, r, out);
    subdivide(x0, zm, x1, z1, depth - 1, r, out);
  }
}

function buildTiles(): Tile[] {
  const r = rng(20260729);
  const rects: Array<[number, number, number, number]> = [];
  subdivide(-11, -11, 11, 11, 6, r, rects);

  // Kind is chosen by area and position rather than a repeating list: large
  // tiles are the structural wall and stay plain, small ones carry the detail.
  // Brand-coloured tiles are rare — the reference's wall is overwhelmingly pale.
  return rects.map(([x0, z0, x1, z1], idx) => {
    const w = x1 - x0 - SEAM;
    const l = z1 - z0 - SEAM;
    const area = w * l;
    // Weighting matters more than it looks. At the first cut the wall carried
    // ~24% document and chart tiles and read as a desk covered in paperwork,
    // where the reference's wall is overwhelmingly plain with occasional
    // accents — ruled paper and chart lines are punctuation, not the surface.
    const u = r();
    let kind: Kind = 'plain';
    // Verified in three seconds of the pass-7 analysis: the reference keeps
    // large SOLID blue and yellow tiles immediately beside its heroes, while
    // the probabilistic wall almost never landed an accent next to the
    // subject. Force the two mid-size tiles nearest the acting area (per the
    // fixed seed) into brand colours.
    const cx = (x0 + x1) / 2;
    const cz = (z0 + z1) / 2;
    // Mid-size tiles only, sparse — the per-shot brandRadius gate below trims
    // them to the acting area in WORLD space (this test runs pre-offset, which
    // is how round one parked a giant gold tile mid-frame in shot 2).
    // Sized down from area 3-8 after measuring the reference at f30: its brand
    // accents are TILE-scale objects a third the width of a hero plate, where
    // ours were filling a quarter of the frame each and reading as walls of
    // paint. The same ceiling now gates the probabilistic accents, which were
    // free to land on the largest tiles in the set.
    const accent = area > 1.3 && area < 3.6 && idx % 4 === 0;
    const canBrand = area < 4.2;
    if (accent) kind = cx < 0 ? 'blue' : 'gold';
    else if (area > 14) kind = 'plain';
    else if (u > 0.94) kind = canBrand ? 'gold' : 'plain';
    else if (u > 0.89) kind = canBrand ? 'blue' : 'plain';
    else if (u > 0.84) kind = canBrand ? 'lightblue' : 'plain';
    else if (u > 0.76) kind = 'metal';
    else if (u > 0.68) kind = 'dots';
    else if (u > 0.63) kind = 'doc';
    else if (u > 0.60) kind = 'chart';
    return {
      x: (x0 + x1) / 2,
      z: (z0 + z1) / 2,
      w,
      l,
      // Steps are small and quantised. The reference's tiles sit within a few
      // millimetres of each other; continuous random heights read as rubble.
      step: [0, 0.018, 0.036, 0.054][Math.floor(r() * 4)],
      kind,
    };
  });
}

export const SetDressing: React.FC<{
  whiten?: number;
  offset?: [number, number, number];
  /**
   * Radius beyond which brand-coloured accents are suppressed. The wide lockup
   * frames a much larger area, so outlying accents land on the frame border —
   * the reference keeps its borders neutral through that shot.
   */
  brandRadius?: number;
  /**
   * Lockup mode: plain tiles only. The reference's final 6.4 seconds play
   * against a clean pale tile wall with a lot of empty space; this scene was
   * putting a pile of documents, chart lines and "Success rate 99.999%" behind
   * the lockup instead, over 44% of the runtime.
   */
  plainOnly?: boolean;
  /**
   * Accent colour allowed near the hero this shot. The reference CONTRASTS:
   * the gold Recurly hero sits among blue accents, the blue Hyperswitch hero
   * among gold — a same-hue accent tile behind the hero merges with it (a
   * giant blue field behind the blue card at f220 was the failure).
   */
  heroAccent?: 'gold' | 'blue' | 'both';
  /**
   * T.assemble progress, 0..1. The reference's lockup cut lands while the
   * WHOLE grid is still converging into the flat arrangement (spec f240,
   * "wide flat view forms") — measured as most of its t=8.0-8.5 motion
   * (A 7.6 vs B 2.0 mean delta with only the two cards travelling). At 1 the
   * wall is at rest; below 1 every tile sits radially expanded and rides the
   * same spring home.
   */
  assemble?: number;
}> = ({ whiten = 0, offset = [0, 0, 0], brandRadius = Infinity, plainOnly = false, heroAccent = 'both', assemble = 1 }) => {
  const tiles = useMemo(buildTiles, []);
  const maps = useMemo(
    () => ({
      plain: panelPlain(3),
      plain2: panelPlain(11),
      dots: panelDots(),
      metal: panelMetal(),
      doc: panelDoc('Billing', 'gold'),
      doc2: panelDoc('Invoices', 'blue'),
      chart: panelChart(),
      blue: panelSolid('#6d8fdd'),
      gold: panelSolid('#f2c93a'),
      lightblue: panelSolid('#a8c1f0'),
    }),
    [],
  );

  const pick = (kind: Kind, i: number): THREE.Texture => {
    switch (kind) {
      case 'dots': return maps.dots;
      case 'metal': return maps.metal;
      case 'doc': return i % 2 ? maps.doc2 : maps.doc;
      case 'chart': return maps.chart;
      case 'blue': return maps.blue;
      case 'gold': return maps.gold;
      case 'lightblue': return maps.lightblue;
      default: return i % 3 === 0 ? maps.plain2 : maps.plain;
    }
  };

  return (
    <group position={offset}>
      {/* Grout fill just below the tile tops. The seam gaps used to look 0.42
          units down an unlit crevice to the underplate, which is where the
          verified near-black spike came from: the render measured p1≈17 in the
          macro seconds against the reference's 48-84. A pale floor 5cm under
          the surface makes seams read as shallow machined joins; the darkening
          that remains comes from AO, which is soft and lit like the reference's. */}
      <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -0.05, 0]} receiveShadow>
        <planeGeometry args={[30, 30]} />
        <meshStandardMaterial color="#98a0ac" roughness={0.9} metalness={0} />
      </mesh>
      {tiles.map((t, i) => {
        const brand = t.kind === 'blue' || t.kind === 'gold' || t.kind === 'lightblue';
        if (brand && Math.hypot(t.x + offset[0], t.z + offset[2]) > brandRadius) return null;
        // Metal tiles used to be exempted from plainOnly. They render as dark
        // navy patches (metalness with nothing to reflect), and one of them sat
        // in the lockup's top-right corner for the whole final shot against a
        // reference whose wall has no dark tile anywhere.
        let kind: Kind = plainOnly && t.kind !== 'plain' ? 'plain' : t.kind;
        if (heroAccent !== 'both' && (kind === 'gold' || kind === 'blue') && kind !== heroAccent) kind = 'plain';
        const metalish = kind === 'metal';
        const isBrand = kind === 'blue' || kind === 'gold' || kind === 'lightblue';
        const spread = 1 + 0.26 * (1 - assemble) * (1 + (i % 3) * 0.3);
        return (
          <Slab
            key={i}
            size={[t.w, TILE_THICK, t.l]}
            radius={Math.min(t.w, t.l) * 0.045}
            position={[t.x * spread, TILE_TOP + t.step - TILE_THICK / 2, t.z * spread]}
            receiveShadow
            castShadow
          >
            <meshPhysicalMaterial
              map={pick(kind, i)}
              roughness={metalish ? 0.34 : isBrand ? 0.42 : 0.62}
              metalness={metalish ? 0.35 : 0.0}
              clearcoat={isBrand ? 0.7 : 0.28}
              clearcoatRoughness={0.42}
              emissive="#ffe6bc"
              emissiveIntensity={whiten}
            />
          </Slab>
        );
      })}
    </group>
  );
};

/**
 * Bezel top for hero wells.
 *
 * Deliberately a hair proud of the tallest tile step rather than flush with
 * TILE_TOP: the tile lattice is fixed at build time and wells are placed per
 * shot, so a flush bezel is simply drawn over by whichever stepped tile happens
 * to overlap it — which is what happened on the first attempt, leaving the hero
 * plates looking pasted onto the wall with no frame at all. Standing proud also
 * matches the reference, whose metal frames have visible thickness and catch a
 * highlight along their top edge.
 */
export const WELL_TOP = TILE_TOP + 0.065;
export const WELL_DEPTH = 0.14;
/** Surface a hero plate rests on, inside the recess. */
export const WELL_FLOOR = WELL_TOP - WELL_DEPTH;

/**
 * A recessed well in the tiled surface: brushed-metal bezel with a sunken floor
 * inside it. Hero plates sit IN this rather than hovering over the set, which
 * is what gives them contact shadow and occlusion to sit in — the "no ambient
 * occlusion" finding that appeared in all fifteen seconds cannot be fixed by
 * lighting alone while nothing in the scene touches anything.
 */
export const Well: React.FC<{
  position: [number, number, number];
  size: [number, number];
  metalMap?: THREE.Texture | null;
  whiten?: number;
  /**
   * The reference's macro hero wells are DARK brushed graphite (verified,
   * sec 6: "dark grey well" vs our light blue-grey); its lockup frames are
   * light silver. Default stays light for the lockup.
   */
  tone?: 'light' | 'dark';
}> = ({ position, size, metalMap = null, whiten = 0, tone = 'light' }) => {
  const [w, l] = size;
  const dark = tone === 'dark';
  // Measured off the reference at f165: the socket border is ~11% of the plate
  // width on each side. 0.24 made it 23% and the hero looked like a small card
  // on a large mat.
  const bezel = dark ? 0.14 : 0.155;
  return (
    <group position={position}>
      <Slab
        size={[w + bezel * 2, TILE_THICK, l + bezel * 2]}
        radius={Math.min(w, l) * 0.07}
        position={[0, WELL_TOP - TILE_THICK / 2, 0]}
        receiveShadow
        castShadow
      >
        {/* Metalness without an environment to reflect renders NEAR-BLACK — at
            0.45 the "dark graphite" bezel came out a flat navy slab, where the
            reference's is clearly brushed mid-grey metal catching the key. The
            brushed character has to come from the map and roughness instead.

            The dark tone's albedo is WARM KHAKI, not neutral. Measured: the
            reference's macro bezel is (117,123,128) — near-neutral and darker
            than the plate; a neutral material under this scene's cool key and
            cool dapple rendered (147,162,197), a full 70 points of blue over
            target. That blue also put the bezel in colour opposition to the
            gold plate, and the out-of-focus edge between them blurred into a
            magenta halo the saturation grade then amplified.

            The light tone's metalness came down from 0.45 for a separate
            reason: the sliver of bezel side wall standing proud of the tile
            tops caught a grazing specular that ran as a hot white bar under
            both brand cards through the entire lockup. The reference's frames
            do carry a bright top edge, but as a highlight on metal, not as a
            light strip. Dropping metalness alone did not shift it; a diagnostic
            render with the bezel tinted red proved the bar belongs to the
            bezel's own +z side wall, where a neighbouring tile at step 0 leaves
            it a full 0.065 proud and its CLEARCOAT lobe mirrors the key
            straight into the lens. Clearcoat is now 0 for BOTH tones: the macro
            bezel kept 0.15 and produced the same defect one scale down — a
            bright white triangular glint at the three-way corner where the
            socket meets a stepped tile, plain enough at t=7.5 to read as a hole
            punched in the set. */}
        <meshPhysicalMaterial
          map={metalMap ?? undefined}
          color={dark ? '#c9bda4' : '#d6dbe4'}
          roughness={dark ? 0.46 : 0.66}
          metalness={dark ? 0.16 : 0.18}
          clearcoat={0}
          anisotropy={0.45}
          emissive="#ffe6bc"
          emissiveIntensity={whiten * 0.5}
        />
      </Slab>
      {/* Well floor. Mid-grey — a charcoal recess reads as a hole punched
          through the set rather than a machined socket. */}
      <Slab
        size={[w, TILE_THICK, l]}
        radius={Math.min(w, l) * 0.09}
        position={[0, WELL_FLOOR - TILE_THICK / 2, 0]}
        receiveShadow
      >
        <meshStandardMaterial color={dark ? '#6f6a60' : '#8f96a3'} roughness={0.88} metalness={0.15} />
      </Slab>
    </group>
  );
};

/**
 * Small out-of-focus cards scattered above the wall at the frame edges, to give
 * the bokeh something to chew on. Kept well outside the acting area and, unlike
 * the tiles, allowed to sit proud — these read as loose paperwork on a desk.
 */
export const Peripherals: React.FC<{ whiten?: number; offset?: [number, number, number] }> = ({ whiten = 0, offset = [0, 0, 0] }) => {
  const items = useMemo(() => {
    const r = rng(778812);
    const out: Array<{ pos: [number, number, number]; size: [number, number, number]; color: string }> = [];
    const ring = [
      [-4.3, 2.6], [-4.9, -1.5], [-3.4, -4.0], [1.2, -4.8], [4.4, -3.1],
      [5.0, 0.9], [3.8, 3.9], [-0.8, 4.9], [-5.4, 4.2], [2.6, 5.6],
      [-6.2, 0.5], [6.0, 3.2], [-2.4, -6.0], [5.6, -5.1],
    ];
    for (const [x, z] of ring) {
      const w = 0.85 + r() * 0.7;
      out.push({
        pos: [x, TILE_TOP + 0.042, z],
        size: [w, 0.085, w * (0.55 + r() * 0.25)],
        color: r() > 0.82 ? '#dbe6fb' : '#ffffff',
      });
    }
    return out;
  }, []);
  return (
    <group position={offset}>
      {items.map((it, i) => (
        <Slab
          key={i}
          size={it.size}
          radius={Math.min(it.size[0], it.size[2]) * 0.2}
          position={it.pos}
          castShadow
          receiveShadow
        >
          <meshPhysicalMaterial
            color={it.color}
            roughness={0.5}
            metalness={0}
            clearcoat={0.5}
            clearcoatRoughness={0.35}
            emissive="#ffe6bc"
            emissiveIntensity={whiten}
          />
        </Slab>
      ))}
    </group>
  );
};
